### ISSUE TITLE
subs() doesn't work correctly with matrices and iterators

### ISSUE THREAD

**Issue by jarthurgross** [sympy/sympy#10589]
Even thought the `subs()` function documentation indicates it can take an arbitrary iterable, sometimes it doesn't work correctly. For example, it will correctly perform multiple substitutions on a `Matrix` if the `(old, new)` pairs are passed as a `list`, but not if they are passed as an `iterator`.

```
In [1]: import sympy as sy

In [2]: x, y = sy.symbols('x y')

In [3]: vect = sy.Matrix([x, y])

In [4]: vect.subs(zip([x, y], [1, 1]))
Out[4]: 
Matrix([
[1],
[y]])

In [5]: vect.subs(list(zip([x, y], [1, 1])))
Out[5]: 
Matrix([
[1],
[1]])
```

I haven't looked at the source, but perhaps it's because the iterator is being exhausted performing the substitutions on the first element of the `Matrix` and is then empty for the remaining elements. If this is the case, a possible solution could be having the first substitution in the iterable applied to all elements in the `Matrix` before moving on the subsequent substitutions in the iterable.

**Comment by leosartaj** [comment]
In current SymPy master,

```
In [1]: import sympy as sy

In [2]: x, y = sy.symbols('x y')

In [3]: vect = sy.Matrix([x, y])

In [4]: vect.subs(zip([x, y], [1, 1]))
Out[4]: 
Matrix([
[1],
[1]])
```

I think the issue is fixed.

**Comment by spirali** [comment]
This issue was not solved. In Python 3.6, the problem still occurs (I have just checked the current master and pip version of sympy). However, it seems that the bug is not manifested in Python 2.

**Comment by oscarbenjamin** [comment]
I see the issue still with SymPy master:
```
In [37]: import sympy as sy                                                                                                                    

In [38]: x, y = sy.symbols('x y')                                                                                                              

In [39]: vect = sy.Matrix([x, y])                                                                                                              

In [40]: vect.subs(zip([x, y], [1, 1]))                                                                                                        
Out[40]: 
⎡1⎤
⎢ ⎥
⎣y⎦

In [41]:  vect.subs(list(zip([x, y], [1, 1])))                                                                                                 
Out[41]: 
⎡1⎤
⎢ ⎥
⎣1⎦
```

From the description in the doc-string I don't know why the input isn't just processed by calling dict on it:
[https://github.com/sympy/sympy/blob/e7ceddb47158fe7fa0f48ed4dd2d34d92e67f846/sympy/core/basic.py#L812](https://github.com/sympy/sympy/blob/e7ceddb47158fe7fa0f48ed4dd2d34d92e67f846/sympy/core/basic.py#L812)

In any case this problem is caused here:
[https://github.com/sympy/sympy/blob/e7ceddb47158fe7fa0f48ed4dd2d34d92e67f846/sympy/matrices/common.py#L1889](https://github.com/sympy/sympy/blob/e7ceddb47158fe7fa0f48ed4dd2d34d92e67f846/sympy/matrices/common.py#L1889)

The subs is called once for each element of the matrix each time passing in the same zip object which is obviously exhausted after the first go. So we can see the same here:
```
In [1]: M = x * ones(5, 5)                                                                                                                     

In [2]: M                                                                                                                                      
Out[2]: 
⎡x  x  x  x  x⎤
⎢             ⎥
⎢x  x  x  x  x⎥
⎢             ⎥
⎢x  x  x  x  x⎥
⎢             ⎥
⎢x  x  x  x  x⎥
⎢             ⎥
⎣x  x  x  x  x⎦

In [3]: M.subs(iter([(x, 1)]))                                                                                                                 
Out[3]: 
⎡1  x  x  x  x⎤
⎢             ⎥
⎢x  x  x  x  x⎥
⎢             ⎥
⎢x  x  x  x  x⎥
⎢             ⎥
⎢x  x  x  x  x⎥
⎢             ⎥
⎣x  x  x  x  x⎦
```

I think the fix is that Matrix.subs should check to see if its argument is a non-sequence iterable and then call list on it if necessary.

**Comment by Naba7** [comment]
I am taking up the issue

**Comment by oscarbenjamin** [comment]
I didn't mean to close this. It happened because of a commit message in #16799. The changes to this there were undone but the commits were still in the PR and one of them referred to this issue.

**Comment by czgdp1807** [comment]
The bug still exists on the `master`,
```python
>>> vect = Matrix([x, y])
>>> vect.subs(zip([x, y], [1, 1]))
⎡1⎤
⎢ ⎥
⎣y⎦
>>> vect.subs(list(zip([x, y], [1, 1])))
⎡1⎤
⎢ ⎥
⎣1⎦ 
```

**Comment by gfolbe318** [comment]
What is the expected behavior of the test case that you wrote? @czgdp1807 
Is the issue related to casting the inputs as a list?

**Comment by jarthurgross** [comment]
I believe the output of the first `subs()` should be the vector full of ones that you actually get after the second `subs()`.

**Comment by jarthurgross** [comment]
The issue as I hypothesized about in the original post is that the iterable containing the pairs defining the substitutions is consumed while performing the substitutions on the first element of the vector, and there are then no substitutions left to perform when it finally gets around to the second element of the vector. Casting it as a list produces the desired behavior, because elements in a list remain in the list even after you've iterated through them.

**Comment by gfolbe318** [comment]
@jarthurgross Thanks for the clarification! That makes a lot of sense. I'm working on generating a pull request for this, but there are a couple of instances of a "subs" function. Do you have any knowledge about which file is causing your specific error?

**Comment by jarthurgross** [comment]
Unfortunately I've never gotten around to digging through the code to find what actually needs to change. Glad to here that you're working on the problem, though!

**Comment by oscarbenjamin** [comment]
Note that there already is a stalled pull request (#16479). Take a look at the changes and the discussion there. It might be worth basing any new work on that PR (with the commits intact for attribution).

**Comment by gfolbe318** [comment]
@oscarbenjamin Thanks! I'll give that a look. Just for reference, what would cause a failed Travis check? I'm pretty new to pull requests.

**Comment by oscarbenjamin** [comment]
Right now the pull request has merge conflicts because it has been sitting for a while and the codebase has moved on so it will no longer merge cleanly. Those are probably not too hard to fix.

The tests originally failed because the other changes did not fix it enough to pass the new test that was added:
```
def test_issue_10589():
    vect = Matrix([x,y])
    assert vect.subs(zip([x,y] , [1,1])) == Matrix([[1], [1]])
```
Looking closer at the changes in the PR I don't think there's any need to base work off of it.

Looking back at the discussion it seems that perhaps we overcomplicated the situation by suggesting to look at all the subs methods around the codebase.

**Comment by gfolbe318** [comment]
That makes sense. Would you recommend starting from scratch in this case?

**Comment by oscarbenjamin** [comment]
Yes

**Comment by gfolbe318** [comment]
Got it! I'm gonna take a crack at it.

**Comment by 0sidharth** [comment]
Shouldn't this be closed?

**Comment by oscarbenjamin** [comment]
Yes
