### ISSUE TITLE
Missing space in the Order class when prinitng with latex

### ISSUE THREAD

**Issue by loeiten** [sympy/sympy#10950]
There seem to be a space missing in the `Order` class when printing with latex.

![screenshot at 2016-04-01 08 58 092](https://cloud.githubusercontent.com/assets/7699917/14200118/fa056f78-f7e8-11e5-9d6f-ddd588fc3c32.png)

**Comment by gxyd** [comment]
It seems to have been fixed in the latest version i.e 1.0 version, SymPy live uses 0.7.6 . You can try that.

**Comment by loeiten** [comment]
Hmm...from the latest release, I still get the problem
![screenshot at 2016-04-01 10 23 552](https://cloud.githubusercontent.com/assets/7699917/14201725/005d09e8-f7f4-11e5-937b-eebc86c6f1a9.png)

**Comment by leosartaj** [comment]
This was fixed after 1.0 was released(#10837). You can try using the development version, if that works for you.

**Comment by loeiten** [comment]
@leosartaj 

Thank you for pointing to the commit for me, I didn't find this when I searched through the issues.

Sorry for the spam.
