### ISSUE TITLE
Change in ccode printing behavior with Eq()

### ISSUE THREAD

**Issue by GitRay** [sympy/sympy#11397]
In the past (v0.7.6), a Piecewise with an Eq() inside would print as:
```
In [1]: from sympy import S, ccode
In [2]: a = S('Eq(a, Piecewise((b, Eq(c, d)), (e, True)))')
In [3]: ccode(a.rhs,assign_to=a.lhs)
Out[3]: 'if (c == d) {\n   a = b;\n}\nelse {\n   a = e;\n}'
```
Now (v1.0), it does the following:
```
>>> from sympy import S, ccode
>>> a = S('Eq(a, Piecewise((b, Eq(c, d)), (e, True)))')
>>> ccode(a.rhs,assign_to=a.lhs)
'if (Eq(c, d)) {\n   a = b;\n}\nelse {\n   a = e;\n}'
```

I am presuming that this is unintended - it is certainly causing me difficulty.

**Comment by cbm755** [comment]
I think this was fixed by @kritkaran94 in 53606796f9dd411a84c9c45ed00fc687c3729b86 and 6e316308cdc694fabac5fc7909be63ad0e0ad644.

Please do reopen if I'm wrong!

**Comment by GitRay** [comment]
I tested with the latest on git (v1.0.1.dev) and the problem persists.

**Comment by kritkaran94** [comment]
@GitRay It works well with the present master branch at Sympy.

````
In [1]: from sympy import S, ccode
In [2]: a = S('Eq(a, Piecewise((b, Eq(c, d)), (e, True)))')
In [3]: ccode(a.rhs,assign_to=a.lhs)
Out[3]: 'if (c == d) {\n   a = b;\n}\nelse {\n   a = e;\n}'
````
I too tested this particular example.

![screen shot 2016-07-18 at 7 01 32 pm](https://cloud.githubusercontent.com/assets/10063868/16916428/732822de-4d1a-11e6-9e8a-8e2d91e1ce1a.png)

**Comment by GitRay** [comment]
My apologies, my git branch was stale.

**Comment by kritkaran94** [comment]
That's okay :)

**Comment by cbm755** [comment]
@GitRay thanks for double-checking and @kritkaran94 thanks for following up!

**Comment by kritkaran94** [comment]
@cbm755 no problem :)
