### ISSUE TITLE
dotprint doesn't use the correct order for x**2

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11634]
The dot diagram in the tutorial is wrong (http://docs.sympy.org/dev/tutorial/manipulation.html). It shows 

```
          Pow
          /  \
Integer(2)    Symbol('x')
```

but it should show

```
           Pow
           /  \
Symbol('x')    Integer(2)
```

since it represents `x**2`, not `2**x`. 

I can't figure out how to make dot give the vertices in the right order. Whatever the fix is, we should fix this in the dot printer as well as the tutorial.

**Comment by asmeurer** [comment]
In the meantime, we should at least change the example to match it (use `2**x`).

**Comment by JainulV** [comment]
@asmeurer should I change all the occurances of x**2 to 2**x in manipulation.rst because they seem to be linked to the same example?

**Comment by asmeurer** [comment]
Yes

**Comment by JainulV** [comment]
Okay working on it

**Comment by bjodah** [comment]
Fixed in #11635

**Comment by asmeurer** [comment]
This only works around the issue. The dotprint function is still wrong.

**Comment by tanayag** [comment]
I am almost complete with the issue

**Comment by tanayag** [comment]
![graphviz-d8d6268439273f5c9659310fcb25b50fd18c6260](https://cloud.githubusercontent.com/assets/16465642/18897712/36233cda-854a-11e6-98d3-f48b3f73f54d.png)

on the website(http://docs.sympy.org/dev/tutorial/manipulation.html),
can't we just change the picture of false dot diagram to the attached one, and change 2**x to x**2 accordingly.

and let it be on doc/src/tutorial/manipulation.rst , whatever it is.

**Comment by JainulV** [comment]
@tanayag I already fixed the tutorial. The only part to focus on making it work correctly.

**Comment by danielrees18** [comment]
@asmeurer Is this still an issue? I looked at fixing this but I didn't seem to see the problem.

Running the example from the docs:
```
>>> from sympy import *
>>> x, y, z = symbols('x y z')
>>> expr = x**2 + x*y
>>> srepr(expr)
>>> "Add(Pow(Symbol('x'), Integer(2)), Mul(Symbol('x'), Symbol('y')))"
```

This seems to be the correct behavior, but I may be wrong? If so, I would be happy to try to fix it.

**Comment by asmeurer** [comment]
The issue is with `dotprint(2**x + x*y)`. The tutorial example was changed to an example that doesn't have the issue.

**Comment by rmagesh148** [comment]
Hi @asmeurer I just tried printing the `dotprint` for `(2**x)` and `(x**2)` but I see the difference in the printing. Please advise me on this. Thank you.
`>>> dotprint(2**x)
\begin{equation*}digraph{

# Graph style
"ordering"="out"
"rankdir"="TD"

#########
# Nodes #
#########

"Pow(Integer(2), Symbol(x))_()" ["color"="black", "label"="Pow", "shape"="ellipse"];
"Integer(2)_(0,)" ["color"="black", "label"="2", "shape"="ellipse"];
"Symbol(x)_(1,)" ["color"="black", "label"="x", "shape"="ellipse"];

#########
# Edges #
#########

"Pow(Integer(2), Symbol(x))_()" -> "Integer(2)_(0,)";
"Pow(Integer(2), Symbol(x))_()" -> "Symbol(x)_(1,)";
}\end{equation*}
\begin{equation*}digraph{# Graph style"ordering"="out""rankdir"="TD"########## Nodes ##########"Pow(Integer(2), Symbol(x))_()" ["color"="black", "label"="Pow", "shape"="ellipse"];"Integer(2)_(0,)" ["color"="black", "label"="2", "shape"="ellipse"];"Symbol(x)_(1,)" ["color"="black", "label"="x", "shape"="ellipse"];########## Edges ##########"Pow(Integer(2), Symbol(x))_()" -> "Integer(2)_(0,)";"Pow(Integer(2), Symbol(x))_()" -> "Symbol(x)_(1,)";}\end{equation*}

>>> dotprint(x**2)
\begin{equation*}digraph{

# Graph style
"ordering"="out"
"rankdir"="TD"

#########
# Nodes #
#########

"Pow(Symbol(x), Integer(2))_()" ["color"="black", "label"="Pow", "shape"="ellipse"];
"Symbol(x)_(0,)" ["color"="black", "label"="x", "shape"="ellipse"];
"Integer(2)_(1,)" ["color"="black", "label"="2", "shape"="ellipse"];

#########
# Edges #
#########

"Pow(Symbol(x), Integer(2))_()" -> "Symbol(x)_(0,)";
"Pow(Symbol(x), Integer(2))_()" -> "Integer(2)_(1,)";
}\end{equation*}`

**Comment by asmeurer** [comment]
Do they give different graphs when you render them with graphviz?

**Comment by rmagesh148** [comment]
Yes. I used [webgraphviz](http://www.webgraphviz.com/) to render the output of `dotprint(x**2)` and `dotprint(2**x)` I was able to see two different graphs

**Comment by Yathartha22** [comment]
@asmeurer I too tried with graphviz it gave two different graphs and the two seemed correct, I guess the dotprinter use the apt order of (x**2). Corrcect me if I am wrong..

**Comment by asmeurer** [comment]
Perhaps something is wrong with the Sphinx extension. Some more debugging is needed.

**Comment by nilinswap** [comment]
@asmeurer should it give different dotdiagrams for dotprint(x+2) and dotprint(2+x)?

**Comment by asmeurer** [comment]
SymPy sorts the arguments of Add and Mul, so 2 + x and x + 2 both create the same expression. It's important to test this with noncommutative operators like Pow.

**Comment by shubham3174** [comment]
@asmeurer I would like to fix this issue. i used dotprint for 2**x and x**2 and it gave two different graph and both seemed correct  . i am not able to see where the bug is . i am new to sympy. which file should i look into...?

**Comment by vishalg2235** [comment]
@asmeurer when I placed line 47:
`"Integer(2)_(1, 1)" ["color"="black", "label"="Integer(2)", "shape"="ellipse"];`
below line 49:
`"Symbol(x)_(1, 0)" ["color"="black", "label"="Symbol('x')", "shape"="ellipse"];`
then the graph generated has 2 on the right side of x.
![graph](https://user-images.githubusercontent.com/17894780/33526198-6eeabada-d863-11e7-8660-60db2486eaa1.png)

**Comment by AbishekSeshan** [comment]
@asmeurer  I'd like to contribute to fix the issue raised, please provide guidelines.
Also, addition is commutative, but still when we traverse through a tree, we go from left to right. Although mathematically it makes no difference, but technically shouldn't Mul and Pow branches be interchanged in the documentation?(Mul being shifted to right and Pow to left).
