### ISSUE TITLE
integrate((cos(3*x)-cos(x))/x, (x, 0, oo)) hangs

### ISSUE THREAD

**Issue by ghost** [sympy/sympy#14078]
The integral evaluates to `-log(3)`

Also: 
`integrate((sin(3*x)-sin(x))/x, (x, 0, oo))` is correctly evaluated to `0`
`integrate((atan(4*x)-atan(2*x))/x, (x, 0, oo))` is returned unevaluated, its value is `pi*log(2)/2`

**Comment by normalhuman** [comment]
We should consider pattern-matching [Frullani integral](https://en.wikipedia.org/wiki/Frullani_integral) (of course, checking the conditions under which the formula applies).

**Comment by Roland-Sands** [comment]
I was thinking of looking at Sage's code and seeing how they calculate integrals

`integrate(x**(2n+1)/(exp(2*pi*x)-1), (x, 0, oo))` can be calculated by multiplying numerator and denominator by `(exp(-2*pi*x)`, then expanding the denominator as a geometric series, then reversing the order of summation and integration, then integrating term-by-term, then identifying the series
Many integrals can be calculated this way (such as `integrate(x**(2*n)/cosh(x), (x, 0, oo))`), but I don't know if it would be suitable for a computer algebra system

**Comment by asmeurer** [comment]
Is there a generalization of Frullani over what is in the Wikipedia article? It doesn't directly apply to the cos integral, although it matches what you would get if you applied the formula blindly with cos(oo) == 0.

**Comment by asmeurer** [comment]
> don't know if it would be suitable for a computer algebra system

It's a neat idea, but I would try to find an example where it computes an integral that cannot otherwise be computed first. SymPy currently doesn't have many summation algorithms. The strongest summation algorithm currently implemented is the same algorithm used to compute integrals (meijerg), so I'm sceptical whether it could compute an integral that couldn't be computed directly.

**Comment by normalhuman** [comment]
@asmeurer  Yes, in the [article](http://www.ams.org/journals/proc/1990-109-01/S0002-9939-1990-1007485-4/S0002-9939-1990-1007485-4.pdf) that Wiki references; the existence of limit of f(x) is relaxed both at 0 and at infinity.

**Comment by Roland-Sands** [comment]
> It's a neat idea, but I would try to find an example where it computes an integral that cannot otherwise be computed first

I gave 2 such examples
As of now,  SymPy cannot do the following 2 integrals, and the method I mentioned can:
`integrate(x**(2n+1)/(exp(2*pi*x)-1), (x, 0, oo))`
`integrate(x**(2*n)/cosh(x), (x, 0, oo))) `
where `n` is a non-negative integer

I can give more if you like

> The strongest summation algorithm currently implemented is the same algorithm used to compute integrals (meijerg), so ...

The summations are pretty easy ones though, such as `Sum((n)**(-2k), (n, 1, oo))`, ones that SymPy can already do, so I don't think that part will be a problem

There is also a generalization of Frullani's formula by Ramanujan, it is in Ramanujan's notebooks part 1 by Bruce Berndt
It is more complicated though, might be difficult to implement

**Comment by normalhuman** [comment]
The integral in the title evaluates to `-log(3)` in current master. The issue with hanging was fixed by #14015.

**Comment by Roland-Sands** [comment]
Should this be closed

**Comment by oscargus** [comment]
It can be closed since the cos-integral evaluates to the correct value. The atan-integral does not hang, but still does not evaluate. I open a new issue for that and close this. New issue:  #17058
