### ISSUE TITLE
ImageSet with tuple is_subset incorrect

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#16878]
```julia
In [12]: ImageSet(Lambda(x, (x, x)), S.Reals)
Out[12]: {(x, x) | x ∊ ℝ}

In [13]: ImageSet(Lambda(x, (x, x)), S.Reals).is_subset(S.Reals**2)
Out[13]: False
```

Also imageset with a tuple and Reals raises:
```julia
In [15]: imageset(x, (x, x), S.Integers)
Out[15]: {(x, x) | x ∊ ℤ}

In [16]: imageset(x, (x, x), S.Reals)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-b7c2358bdf74> in <module>
----> 1 imageset(x, (x, x), S.Reals)

~/current/sympy/sympy.git/sympy/sets/sets.py in imageset(*args)
   1830         try:
   1831             # TypeError if arg count != set dimensions
-> 1832             r = set_function(f, set)
   1833             if r is None:
   1834                 raise TypeError

~/current/sympy/sympy.git/sympy/sets/sets.py in set_function(f, x)
   2057 def set_function(f, x):
   2058     from sympy.sets.handlers.functions import _set_function
-> 2059     return _set_function(f, x)

~/current/sympy/sympy.git/sympy/multipledispatch/dispatcher.py in __call__(self, *args, **kwargs)
    196             self._cache[types] = func
    197         try:
--> 198             return func(*args, **kwargs)
    199 
    200         except MDNotImplementedError:

~/current/sympy/sympy.git/sympy/sets/handlers/functions.py in _set_function(f, x)
     65 
     66     try:
---> 67         sing = [i for i in singularities(expr, var)
     68             if i.is_real and i in x]
     69     except NotImplementedError:

~/current/sympy/sympy.git/sympy/calculus/singularities.py in singularities(expression, symbol)
     81 
     82     """
---> 83     if not expression.is_rational_function(symbol):
     84         raise NotImplementedError(
     85             "Algorithms finding singularities for non-rational"

AttributeError: 'Tuple' object has no attribute 'is_rational_function'
```

**Comment by oscarbenjamin** [comment]
The issues mentioned here have already been fixed in 7e8fbd8849f02f5e813a97c284c3208cfd909f0f from gh-17474.

This issue can be closed if a regression test is added.

**Comment by leastloris** [comment]
@oscarbenjamin I guess the issue is still there. Test was failed
        A = ImageSet(Lambda(x, (x, x)), S.Reals)
        B = S.Reals ** 2
        assert A.is_subset(B)
E       assert None
E        +  where None = is_subset(ProductSet(Reals, Reals))
E        +    where is_subset = ImageSet(Lambda(x, (x, x)), Reals).is_subset

sympy\sets\tests\test_sets.py:1779: AssertionError

**Comment by oscarbenjamin** [comment]
Returning None is fine here because it means "unknown". Returning False or raising an exception was the bug from before.

**Comment by leastloris** [comment]
okay I'll proceed and complete the test accordingly
