### ISSUE TITLE
Recursion error when instantiating exp(gamma(I / acoth(csch(a)))) for large a

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#18075]
After commit 807908fb86cadaac65933d8635e53e140984cad0, simply creating this expression results in a recursion error for any a > 24:

```
>>> from sympy import *
>>> f = lambda a: exp(gamma(I / acoth(csch(a))))
>>> f(24)
exp(gamma(I/acoth(csch(24))))
>>> f(25)
Traceback (most recent call last):
  File "/home/eward/se/sympy/core/assumptions.py", line 262, in getit
    return self._assumptions[fact]
KeyError: 'zero'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eward/se/sympy/core/assumptions.py", line 262, in getit
    return self._assumptions[fact]
KeyError: 'extended_real'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eward/se/sympy/core/assumptions.py", line 262, in getit
    return self._assumptions[fact]
KeyError: 'finite'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eward/se/sympy/core/evalf.py", line 1311, in evalf
    rf = evalf_table[x.func]
KeyError: acoth

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <lambda>
  File "/home/eward/se/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/eward/se/sympy/core/function.py", line 473, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)
  File "/home/eward/se/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/eward/se/sympy/core/function.py", line 288, in __new__
    evaluated = cls.eval(*args)
  File "/home/eward/se/sympy/functions/elementary/exponential.py", line 322, in eval
    if arg.is_zero:
  File "/home/eward/se/sympy/core/assumptions.py", line 266, in getit
    return _ask(fact, self)
  File "/home/eward/se/sympy/core/assumptions.py", line 321, in _ask
    _ask(pk, obj)
  File "/home/eward/se/sympy/core/assumptions.py", line 309, in _ask
    a = evaluate(obj)
  File "/home/eward/se/sympy/core/expr.py", line 910, in _eval_is_extended_negative
    return self._eval_is_extended_positive_negative(positive=False)
  File "/home/eward/se/sympy/core/expr.py", line 875, in _eval_is_extended_positive_negative
    if self.is_extended_real is False:
  File "/home/eward/se/sympy/core/assumptions.py", line 266, in getit
    return _ask(fact, self)
  File "/home/eward/se/sympy/core/assumptions.py", line 321, in _ask
    _ask(pk, obj)
  File "/home/eward/se/sympy/core/assumptions.py", line 309, in _ask
    a = evaluate(obj)
  File "/home/eward/se/sympy/core/expr.py", line 862, in _eval_is_negative
    finite = self.is_finite
  File "/home/eward/se/sympy/core/assumptions.py", line 266, in getit
    return _ask(fact, self)
  File "/home/eward/se/sympy/core/assumptions.py", line 321, in _ask
    _ask(pk, obj)
  File "/home/eward/se/sympy/core/assumptions.py", line 321, in _ask
    _ask(pk, obj)
  File "/home/eward/se/sympy/core/assumptions.py", line 309, in _ask
    a = evaluate(obj)
  File "/home/eward/se/sympy/functions/special/gamma_functions.py", line 176, in _eval_is_real
    if intlike(x) and x <= 0:
  File "/home/eward/se/sympy/functions/special/gamma_functions.py", line 21, in intlike
    as_int(n, strict=False)
  File "/home/eward/se/sympy/core/compatibility.py", line 420, in as_int
    result = int(n)
  File "/home/eward/se/sympy/core/expr.py", line 294, in __int__
    r = self.round(2)
  File "/home/eward/se/sympy/core/expr.py", line 3642, in round
    return i.round(n) + S.ImaginaryUnit*r.round(n)
  File "/home/eward/se/sympy/core/expr.py", line 3642, in round
    return i.round(n) + S.ImaginaryUnit*r.round(n)
  File "/home/eward/se/sympy/core/expr.py", line 3642, in round
    return i.round(n) + S.ImaginaryUnit*r.round(n)
  [Previous line repeated 918 more times]
  File "/home/eward/se/sympy/core/expr.py", line 3635, in round
    if not pure_complex(x.n(2), or_real=True):
  File "/home/eward/se/sympy/core/evalf.py", line 1445, in evalf
    result = evalf(self, prec + 4, options)
  File "/home/eward/se/sympy/core/evalf.py", line 1312, in evalf
    r = rf(x, prec, options)
  File "/home/eward/se/sympy/core/evalf.py", line 564, in evalf_mul
    arg = evalf(arg, prec, options)
  File "/home/eward/se/sympy/core/evalf.py", line 1312, in evalf
    r = rf(x, prec, options)
  File "/home/eward/se/sympy/core/evalf.py", line 681, in evalf_pow
    re, im, re_acc, im_acc = evalf(base, prec + 5, options)
  File "/home/eward/se/sympy/core/evalf.py", line 1312, in evalf
    r = rf(x, prec, options)
  File "/home/eward/se/sympy/core/evalf.py", line 524, in evalf_add
    terms = [evalf(arg, prec + 10, options) for arg in v.args]
  File "/home/eward/se/sympy/core/evalf.py", line 524, in <listcomp>
    terms = [evalf(arg, prec + 10, options) for arg in v.args]
  File "/home/eward/se/sympy/core/evalf.py", line 1312, in evalf
    r = rf(x, prec, options)
  File "/home/eward/se/sympy/core/evalf.py", line 681, in evalf_pow
    re, im, re_acc, im_acc = evalf(base, prec + 5, options)
  File "/home/eward/se/sympy/core/evalf.py", line 1312, in evalf
    r = rf(x, prec, options)
  File "/home/eward/se/sympy/core/evalf.py", line 255, in evalf_im
    return get_complex_part(expr.args[0], 1, prec, options)
  File "/home/eward/se/sympy/core/evalf.py", line 237, in get_complex_part
    res = evalf(expr, workprec, options)
  File "/home/eward/se/sympy/core/evalf.py", line 1317, in evalf
    xe = x._eval_evalf(prec)
  File "/home/eward/se/sympy/core/function.py", line 603, in _eval_evalf
    return Expr._from_mpmath(v, prec)
  File "/home/eward/se/sympy/core/expr.py", line 415, in _from_mpmath
    im = Float._new(im, prec)*S.ImaginaryUnit
  File "/home/eward/se/sympy/core/decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)
  File "/home/eward/se/sympy/core/numbers.py", line 1313, in __mul__
    return Number.__mul__(self, other)
  File "/home/eward/se/sympy/core/decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)
  File "/home/eward/se/sympy/core/numbers.py", line 757, in __mul__
    return AtomicExpr.__mul__(self, other)
  File "/home/eward/se/sympy/core/decorators.py", line 91, in __sympifyit_wrapper
    return func(a, b)
  File "/home/eward/se/sympy/core/decorators.py", line 129, in binary_op_wrapper
    return func(self, other)
  File "/home/eward/se/sympy/core/expr.py", line 196, in __mul__
    return Mul(self, other)
  File "/home/eward/se/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/eward/se/sympy/core/numbers.py", line 1395, in __eq__
    if not self:
  File "/home/eward/se/sympy/core/numbers.py", line 1287, in __nonzero__
    return self._mpf_ != fzero
RecursionError: maximum recursion depth exceeded in comparison
```

**Comment by oscarbenjamin** [comment]
This is to do with `is_extended_real` somehow:
```julia
In [12]: f = lambda a: re(acoth(csch(a)))/(re(acoth(csch(a)))**2 + im(acoth(csch(a)))**2)                                         

In [13]: f(25)                                                                                                                    
Out[13]: 
            re(acoth(csch(25)))            
───────────────────────────────────────────
  2                      2                 
re (acoth(csch(25))) + im (acoth(csch(25)))

In [14]: f(25).is_extended_real                                                                                                   

In [15]: f(24).is_extended_real                                                                                                   
Out[15]: True

In [16]: f(25).n()                                                                                                                
Out[16]: 1.12571432860520e-11

In [17]: f(24).n()                                                                                                                
Out[17]: 3.06000880348348e-11
```

**Comment by oscarbenjamin** [comment]
`re(acoth(csch(25)))` gives `True` incorrectly

**Comment by oscarbenjamin** [comment]
I meant to say that is_zero gives True incorrectly:
```julia
In [1]: re(acoth(csch(25))).is_zero                                                                                               
Out[1]: True

In [2]: re(acoth(csch(25))).evalf()                                                                                               
Out[2]: 2.77758877299287e-11
```

**Comment by oscarbenjamin** [comment]
The bug is in evalf:
```
In [2]: re(acoth(csch(25))).evalf(2)                                                                                              
Out[2]: 0

In [3]: re(acoth(csch(25))).evalf(10)                                                                                             
Out[3]: 2.777588771e-11
```

**Comment by oscarbenjamin** [comment]
There are two bugs: `re(acoth(csch(25))).evalf(2)` incorrectly gives `0` and also this line leads to infinite recursion if `is_extended_real` gives `None`:
https://github.com/sympy/sympy/blob/2d3ca2aa7e94796855277ca710999efe143485d4/sympy/core/expr.py#L3640-L3642

**Comment by oscarbenjamin** [comment]
It's not to do with `re`:
```julia
In [10]: acoth(csch(25)).evalf(2)                                                                                                 
Out[10]: -1.6⋅ⅈ
```

**Comment by oscargus** [comment]
This seems to have been fixed in the current `master` so just to add a test and close.

**Comment by oscarbenjamin** [comment]
The bug is that `evalf(2)` gives a zero real part:
```python
In [5]: acoth(csch(25)).evalf(10)
Out[5]: 2.777588771e-11 - 1.570796327⋅ⅈ

In [6]: acoth(csch(25)).evalf(2)
Out[6]: -1.6⋅ⅈ
```
That bug is still present on master.

**Comment by oscargus** [comment]
Ahh, OK. But the issue in the title is fixed at least.

**Comment by oscargus** [comment]
It seems like the resolution required for "cascaded" transcendental functions is not really that stable:


```
print(acoth(csch(25)).rewrite(log).evalf(2))
print(acoth(csch(25)).rewrite(exp).evalf(2))
print(acoth(csch(25)).rewrite(log).evalf(10))
print(acoth(csch(25)).rewrite(exp).evalf(10))
```
gives
```
0.e-6 - 1.6*I
2.9e-11 - 1.6*I
2.78e-11 - 1.570796327*I
2.777588771e-11 - 1.570796327*I
```

**Comment by oscarbenjamin** [comment]
I think that `0.e-6` is okay even if a 2-digit result would be better. At least it shows that there are no correct digits. Returning a definite zero for the real part is not okay though:
```python
In [11]: re(acoth(csch(25)).rewrite(log).evalf(2))
Out[11]: 0.e-6

In [12]: re(acoth(csch(25)).evalf(2))
Out[12]: 0
```
There are a lot of calls to `evalf(2)` around the codebase so it needs to be dependable.

This could be considered a bug in mpmath:
```python
In [33]: with mpmath.workprec(14):
    ...:     v = mpmath.acoth(2.7775892696979554e-11)
    ...: 

In [34]: v
Out[34]: mpc(real='0.0', imag='-1.570801')

In [35]: v._mpc_
Out[35]: ((0, mpz(0), 0, 0), (1, mpz(3217), -11, 12))

In [36]: print(v)
(0.0 - 1.571j)
```
On the other hand maybe evalf should detect this case and attempt higher precision for the imaginary part. It's hard to know because mpmath doesn't directly give any indication that there might be a small imaginary part.

This is probably why interval/ball arithmetic is better than evalf's approach to significance arithmetic. Unfortunately mpmath hasn't implemented this particular function for interval arithmetic:
```python
In [37]: mpmath.iv.acoth(2.7775892696979554e-11)
---------------------------------------------------------------------------
AttributeError 
```
