### ISSUE TITLE
IndexError in matrix exponential

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#19210]
From stackoverflow: https://stackoverflow.com/questions/61461512/sympy-exp-i-h-t-error-mutabledensematrix

```
>>> import sympy
>>> t=sympy.Symbol('t')
>>> H=sympy.Matrix([[3, 0, 0, 0], [0, 1 , 2, 0], [0, 2, 2, 0], [0, 0, 0, 4]])
>>> A = sympy.exp(-sympy.I * H * t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/enojb/current/sympy/sympy/sympy/core/function.py", line 465, in __new__
    result = super().__new__(cls, *args, **options)
  File "/Users/enojb/current/sympy/sympy/sympy/core/function.py", line 280, in __new__
    evaluated = cls.eval(*args)
  File "/Users/enojb/current/sympy/sympy/sympy/functions/elementary/exponential.py", line 323, in eval
    return arg.exp()
  File "/Users/enojb/current/sympy/sympy/sympy/matrices/matrices.py", line 1621, in exp
    P, J = self.jordan_form()
  File "/Users/enojb/current/sympy/sympy/sympy/matrices/matrices.py", line 411, in jordan_form
    return _jordan_form(self, calc_transform=calc_transform, **kwargs)
  File "/Users/enojb/current/sympy/sympy/sympy/matrices/eigen.py", line 981, in _jordan_form
    jordan_basis = [eig_mat(eig, 1).nullspace()[0]
  File "/Users/enojb/current/sympy/sympy/sympy/matrices/eigen.py", line 981, in <listcomp>
    jordan_basis = [eig_mat(eig, 1).nullspace()[0]
IndexError: list index out of range
```

**Comment by abhinav28071999** [comment]
In the current master `H.analytic_func(exp(x*t*-I), x)` gives the answer. Not sure if it is correct.

**Comment by oscarbenjamin** [comment]
I think it is correct:
```julia
In [25]: Hexp = H.analytic_func(exp(x*t*-I), x)                                                                                                

In [26]: simplify(Hexp.diff(t) + I*H*Hexp)                                                                                                     
Out[26]: 
⎡0  0  0  0⎤
⎢          ⎥
⎢0  0  0  0⎥
⎢          ⎥
⎢0  0  0  0⎥
⎢          ⎥
⎣0  0  0  0⎦
```
That doesn't really fix this issue though which is a bug in `jordan_form`/`eigenvectors`:
```julia
In [24]: (-I*H*t).jordan_form()                                                                                                                
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-24-14eb7e34f75e> in <module>
----> 1 (-I*H*t).jordan_form()

~/current/sympy/38venv/lib/python3.8/site-packages/sympy/matrices/matrices.py in jordan_form(self, calc_transform, **kwargs)
    409 
    410     def jordan_form(self, calc_transform=True, **kwargs):
--> 411         return _jordan_form(self, calc_transform=calc_transform, **kwargs)
    412 
    413     def left_eigenvects(self, **flags):

~/current/sympy/38venv/lib/python3.8/site-packages/sympy/matrices/eigen.py in _jordan_form(M, calc_transform, **kwargs)
    979             return restore_floats(jordan_mat)
    980 
--> 981         jordan_basis = [eig_mat(eig, 1).nullspace()[0]
    982                 for eig in blocks]
    983         basis_mat    = mat.hstack(*jordan_basis)

~/current/sympy/38venv/lib/python3.8/site-packages/sympy/matrices/eigen.py in <listcomp>(.0)
    979             return restore_floats(jordan_mat)
    980 
--> 981         jordan_basis = [eig_mat(eig, 1).nullspace()[0]
    982                 for eig in blocks]
    983         basis_mat    = mat.hstack(*jordan_basis)

IndexError: list index out of range
```

**Comment by praneethratna** [comment]
This is fixed by c82e87d7d07f9eddee8ae1b9226d2de69e6c4dbd in #19355 , On current master:
```
>>> (-I*H*t).jordan_form()
(Matrix([
[0, 1,                  0,                0],
[0, 0, -4/(-1 + sqrt(17)), 4/(1 + sqrt(17))],
[0, 0,                  1,                1],
[1, 0,                  0,                0]]), Matrix([
[-4*I*t,      0,                         0,                         0],
[     0, -3*I*t,                         0,                         0],
[     0,      0, t*(-3*I/2 + sqrt(17)*I/2),                         0],
[     0,      0,                         0, t*(-sqrt(17)*I/2 - 3*I/2)]]))
```

**Comment by smichr** [comment]
this can be closed with a test

**Comment by oscarbenjamin** [comment]
I think maybe the underlying issue remains. It's just not hitting the same codepath any more.

**Comment by oscarbenjamin** [comment]
Actually I see that that commit does fix this. The problem was that the eigenvalues were coming out much more complicated involving Piecewise. There have been two improvements here. One is https://github.com/sympy/sympy/commit/c82e87d7d07f9eddee8ae1b9226d2de69e6c4dbd which means that the matrix is split into smaller components so it doesn't try to find the roots of a quartic any more. The other is f264880bf9389deaea9e3a2435540cb6f69f614e which means that the roots of the quartic are found through factorisation:
```python
In [1]: roots(
   ...:     -24 * t ** 4
   ...:     + 22 * I * t ** 3 * z
   ...:     - 31 * t ** 2 * z ** 2
   ...:     - 10 * I * t * z ** 3
   ...:     + z ** 4,
   ...:     z,
   ...: )
Out[1]: 
⎧                      ⎛3⋅ⅈ   √17⋅ⅈ⎞       ⎛  √17⋅ⅈ   3⋅ⅈ⎞   ⎫
⎨3⋅ⅈ⋅t: 1, 4⋅ⅈ⋅t: 1, t⋅⎜─── + ─────⎟: 1, t⋅⎜- ───── + ───⎟: 1⎬
⎩                      ⎝ 2      2  ⎠       ⎝    2      2 ⎠   ⎭
```

**Comment by aaditkamat** [comment]
Is this issue still open?

**Comment by MohitKumar020291** [comment]
> Is this issue still open?

Yes @aaditkamat it is open and thanks for showing your interest.

**Comment by perfectdash** [comment]
#19210 sorry I forgot to make a pull request

**Comment by Aditya-Naresh** [comment]
Is this still open??

**Comment by 1e9abhi1e10** [comment]
> Is this still open??

@Aditya-Naresh This issue is fixed by #24863. You can try other issues which are open.
