### ISSUE TITLE
stats.sample(N, size=2) returns float not list

### ISSUE THREAD

**Issue by xsamgreen** [sympy/sympy#19473]
Hi,

When I run the [stats.sample example code](https://docs.sympy.org/latest/modules/stats.html#sympy.stats.sample):
```
from sympy.stats import sample, Normal
N = Normal('N', 3, 4)
samp_list = sample(N, size=4)
```
it returns a `sympy.core.numbers.Float` not an iterable as would be expected:
```
print(samp_list)
6.24252739372565
```

This is true with SymPy versions 1.1.1 and 1.5.1.

Note that this can be worked around by using [stats.sample_iter](https://docs.sympy.org/latest/modules/stats.html#sympy.stats.sample_iter).

**Comment by Smit-create** [comment]
Hi,
There has been a change in the `sample` of stats after the release of 1.6.
On current master, this has been fixed, and the new change is that `sample` now returns an iterable object and uses `scipy/numpy` for sampling.
Presently(on the current master) it works as:
```python
>>> from sympy.stats import *
>>> N = Normal('N', 3, 4)
>>> samp_list = list(sample(N, size=4))
>>> samp_list
[array([8.09960443, 0.45603657, 1.1669486 , 5.38151957])]
```

**Comment by xsamgreen** [comment]
Hi @Smit-create,

Thanks for responding. I just cloned the current master and tried it, but I'm still having problems:

```
>>> import sympy
>>> sympy.__version__
'1.7.dev'
>>> from sympy.stats import *
>>> N = Normal('N', 3, 4)
>>> samp_list = list(sample(N, size=4))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sam/working/sp2/sympy/stats/rv.py", line 1090, in sample
    return sample_iter(expr, condition, size=size, library=library,
  File "/home/sam/working/sp2/sympy/stats/rv.py", line 1183, in sample_iter
    raise ValueError("Failed to import %s" % library)
ValueError: Failed to import scipy
```

**Comment by Smit-create** [comment]
It's because sampling of sympy random variables now uses numeric libraries `scipy/numpy` for sampling.

**Comment by xsamgreen** [comment]
I see. I had misread "scipy" as "sympy" in that value error. Thanks for your help!
