### ISSUE TITLE
SymPy can't solve a basic compound interest type problem

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#2999]
```
In [30]: solve(10*(1 + 0.1/12)**(12*x) - 20, x)
Out[30]: []
```

(it doesn't work if I use rationals either)

If I compound quarterly, I get a solution:

```py
In [32]: solve(10*(1 + 0.1/4)**(4*x) - 20, x)
Out[32]: [7.01775863148466]
```

I also get a solution if I use a symbolic value:

```py
In [40]: solve(10*(1 + 0.1/n)**(n*x) - 20, x)
Out[40]:
⎡           0.693147180559945            ⎤
⎢────────────────────────────────────────⎥
⎢  ⎛   ⎛10.0⋅n + 1.0⎞                   ⎞⎥
⎢n⋅⎜log⎜────────────⎟ - 2.30258509299405⎟⎥
⎣  ⎝   ⎝     n      ⎠                   ⎠⎦
```

**Comment by hargup** [comment]
The issue is fixed with `solveset`
```python
In [25]: solveset_real(10*(1 + S(1)/120)**(12*x) - 20, x)
Out[25]: {log(2)/(12*(-log(120) + log(121)))}
```

**Comment by asmeurer** [comment]
But it still doesn't work with `solve`. Are we assuming that solve is defunct and issues with it that work in solveset aren't worth fixing?  I think this should remain open, especially since `check=False` does give an answer.

**Comment by hargup** [comment]
> Are we assuming that solve is defunct and issues with it that work in solveset aren't worth fixing? 

I don't want people to spend time fixing `solve` rather that time should go in improving `solveset`. In it is current state it is very hard to make changes to `solve` and its original developers agree which is mainly you and @smichr I would like to declare `solve` as defunct, not necessarily now but at least some time in future.

**Comment by asmeurer** [comment]
That's fine with me. If we do that we should document it, and also put the replacement functions in the sympy namespace.
