### ISSUE TITLE
Allow to set min_fixed and max_fixed for Float in the printers

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#7847]
The mpmath printer has `min_fixed` and `max_fixed` settings, which should be exposed to the printers. Right now, only the `strip_zeros` option is exposed. 

We should also unify the Float printer for the various printers. For example, the LaTeX printer doesn't have the same behavior as the string printer.

**Comment by lohmanndouglas** [comment]
@MridulS  Hello the bug has been fixed? 
If not, would like to know more information to resolve this bug. You need help to implement anything else?

**Comment by moorepants** [comment]
@lohmanndouglas You could add @MridulS's github fork of sympy as a remote and pull down his branch with his fix in https://github.com/sympy/sympy/issues/7847. Then play with it and see if it works.

**Comment by MridulS** [comment]
@moorepants unfortunately i have deleted that branch. @lohmanndouglas you can still see the changes I tried at https://github.com/sympy/sympy/commit/61838749a78082453be4e779cb68e88605d49244

**Comment by Yathartha22** [comment]
Is this issue fixed? I would like to take this on.

**Comment by lzkelley** [comment]
@Yathartha22 I think this is still open, if you're still interested --- though it's been a while...

The [SO question that (partially) prompted this has over 1000 views](https://stackoverflow.com/questions/25222681/scientific-exponential-notation-with-sympy-in-an-ipython-notebook) now.

**Comment by Yathartha22** [comment]
Sure I will take this up.

**Comment by m-agboola** [comment]
Is this issue fixed? If not I'd like to work on it.

**Comment by asmeurer** [comment]
I don't think so. I don't see any cross-referenced pull requests listed here.

**Comment by mijo2** [comment]
@asmeurer according to this https://stackoverflow.com/questions/25222681/scientific-exponential-notation-with-sympy-in-an-ipython-notebook I tried exposing the ```min``` and ```max``` fixed from ```mpmath``` to ```StrPrinter``` but currently we have to set the exponent values as ```min``` and ```max```. For example, to print in a fixed-point format for numbers between ```[0.01, 100]```, we can do it by passing additional ```min```, ```max``` in ```StrPrinter``` object. The demonstration is below:

![github_issue_7847_1](https://user-images.githubusercontent.com/25644913/73141188-33bd9500-40a7-11ea-86e1-e0cc74194e4d.png)

As you can see, the exponent check is like if exponent is in ```(-2, 2)``` then it will print fixed-point format else floating-point format.

Should I expose these options in other printers as well?

**Comment by lzkelley** [comment]
@mijo2 why is `0.04` still printing as `4.0e-2`?  And is there a separate parameter for the 'sig-figs' (i.e. `55.0` vs `55` or `55.`?

**Comment by mijo2** [comment]
@lzkelley 0.04 is printed as 4e-2 because when we mention min as -2 and max as 2, then all the numbers between 0.1 and 100 where 0.1 inclusive and 100 exclusive, are printed in fixed-point floating format. That is why 0.04 is printed as 4e-2. These min and max parameters are straight from mpmath's to_str method that we are using in StrPrinter

**Comment by lzkelley** [comment]
Okay, the asymmetry is a little weird to me, but sure.

So is it possible to have `max` and `min` set in `init_printing()` via `Printer.set_global_settings()` or something like that?

**Comment by mijo2** [comment]
@Izkelley let me try it out and get back to you regarding this.

**Comment by mijo2** [comment]
@lzkelley So, when I made the changes and exposed the ```min``` and ```max``` options for string and latex printers, it became possible to set ```max``` and ```min``` via ```Printer.set_global_settings()```.

Example:
```
>>> Printer.set_global_settings(min=-2, max=4)
>>> obj = StrPrinter()
>>> obj._print(Float('100'))
'100.000000000000'
>>> obj._print(Float('10000'))
'1.00000000000000e+4'
```
