### ISSUE TITLE
Using and operator vs fuzzy_and while querying assumptions

### ISSUE THREAD

**Issue by skirpichev** [sympy/sympy#8500]
The problem is that builtin and operator is not symmetric wrt non-boolean args, esp. None:

``` python
In [1]: from sympy.core.logic import fuzzy_and

In [2]: None and False

In [3]: False and None
Out[3]: False

In [4]: fuzzy_and([None, False])
Out[4]: False

In [5]: fuzzy_and([False, None])
Out[5]: False
```

That's important if we consider assumptions.  We have a lot of statements like `self.is_integer and other.is_integer` in the code (see, for example, [some cases](https://gist.githubusercontent.com/skirpichev/03fb41f52bcc6d3653df/raw/06c8df41ccc0200e2091c9cdfb7c48682416233a/a.log) in the core).  It seems, this is a wrong pattern and we should use `fuzzy_and` instead.

Thanks to @smichr who brings my attention to this in https://github.com/sympy/sympy/pull/8490.

**Comment by skirpichev** [comment]
No activity.  I believe, this is fixed in the diofant, so it's not a problem for me.  Closed.

**Comment by smichr** [comment]
Although this may not be a problem for diofant it should be checked in SymPy to see if these issue still exist.
